[phases.setup]
nixPkgs = ['python311', 'gcc', 'pkg-config', 'libpq']

[phases.install]
cmds = [
    'python -m venv --copies /opt/venv',
    '. /opt/venv/bin/activate && pip install -r requirements.txt'
]

[phases.build] 
cmds = [
    'mkdir -p data/indexes',
    'mkdir -p models'
]

[start]
cmd = 'alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT'